/**
 * Jamal deployment command.
 *
 * Jamal wraps the deploy-generator registry behind a small, human-first CLI.
 * `jamal dev` plans the local development set (Valkey + database Docker
 * Compose); `jamal deploy` on the default Docker/SSH (kamal) engine EXECUTES a
 * production release by default (`--dry-run` prints the pure engine plan), while
 * a static hosting target (`--target vercel|netlify|cloudflare|github`, plus any
 * custom deployment generator declared in the app config's `deployments` array)
 * only generates files and requires `--write` to materialize them; the built-in
 * static targets (`vercel`/`netlify`/`cloudflare`) then EXECUTE their deploy
 * through `npx` — `github` is push-based and stays a workflow + hint. `jamal
 * targets` lists every available target without running one. Static and custom
 * targets are never deployed by jamal — the generated files are deployed with
 * the host's own CLI (e.g. `npx vercel deploy --prod`). `rollback` executes by
 * default with `--dry-run` as its preview.
 *
 * Custom targets are merged after the built-ins by loading `jsails.app.js`
 * (trusted app code) when it exists; a custom name that collides with a
 * built-in generator id is rejected.
 *
 * Production is the DEFAULT: `jamal deploy` runs a production release (Kamal),
 * or generates a static host's files via `--target`, while `jamal dev` is the
 * explicit local-development override. Jamal never auto-detects an environment
 * — the user names it. The Sail-like execution verbs (`up`, `down`, `ps`,
 * `logs`) drive the local Compose project generated by `dev --write` and are
 * the one place jamal spawns `docker compose`; see `src/jamal/docker.ts`.
 */

import { parseArgs } from 'node:util';

import { runAccessoryCommand } from './accessory.js';
import { runAppCommand } from './app.js';
import { runDomainCommand } from './domain.js';
import { isDockerVerb } from './docker.js';
import {
  runDeployCommand,
  runDockerExec,
  runDockerVerb,
  runRemoteStatusVerb,
  runRollbackCommand,
  routeRemoteLogsOrExec,
} from './exec.js';
import {
  defaultJamalDeps,
  formatError,
  runPlanCommand,
  runTargets,
  type JamalDeps,
  usageError,
} from './plan-command.js';
import type { JamalConfig } from './config.js';
import { planRegistryLogin, formatRegistryLoginPlan, type RegistryLoginPlan } from './registry.js';
import { planPrune, formatPrunePlan, type ImageRef } from './prune.js';
import { planAudit, formatAuditPlan } from './audit.js';
import { planSnapshot, planRestore, formatSnapshotPlan, type SnapshotDriver } from './snapshot.js';
import { JAMAL_DEPLOY_USAGE, JAMAL_USAGE } from './usage.js';
import { loadJamalConfig } from './config.js';

// Public surface: this module is the jamal command's entry point. The planning
// flows live in `plan.ts`, the execution verbs in `exec.ts`, and the help text
// in `usage.ts`; re-export the shared seam so consumers import the same symbols
// from here as before the split.
export { JamalError, defaultJamalDeps } from './plan-command.js';
export type { JamalDeps } from './plan-command.js';

const JAMAL_OPTIONS = {
  write: { type: 'boolean', default: false },
  dir: { type: 'string' },
  target: { type: 'string', default: 'kamal' },
  detach: { type: 'boolean', default: false },
  follow: { type: 'boolean', default: false },
  'dry-run': { type: 'boolean', default: false },
  tag: { type: 'string' },
  help: { type: 'boolean', short: 'h', default: false },
  keep: { type: 'string' },
  images: { type: 'string', multiple: true },
  name: { type: 'string' },
  snapshot: { type: 'string' },
  driver: { type: 'string' },
} as const;

/**
 * Run the `jamal` command over the tokens after the `jamal` command name.
 * Resolves to a process exit code: 0 on success (including a dry run, a
 * `targets` listing, a run where files were skipped, and a clean `docker
 * compose` execution), 2 for usage errors, 1 for a generation/write failure
 * or a spawn failure, 127 when docker compose is unavailable, and the child's
 * own exit code when a compose verb fails. Help and usage paths never build
 * the registry, run a generator, or spawn a process.
 */
export async function runJamalCommand(
  args: readonly string[],
  deps: JamalDeps = defaultJamalDeps,
): Promise<number> {
  // `accessory` and `domain` own their own flag sets and positional shapes, so
  // they are routed before the shared `parseArgs` gate (which would reject their
  // flags).
  if (args[0] === 'accessory') {
    return runAccessoryCommand(deps, args.slice(1));
  }
  if (args[0] === 'domain') {
    return runDomainCommand(deps, args.slice(1));
  }
  if (args[0] === 'app') {
    return runAppCommand(deps, args.slice(1));
  }

  let parsed;
  try {
    parsed = parseArgs({
      args: [...args],
      options: JAMAL_OPTIONS,
      allowPositionals: true,
      strict: true,
    });
  } catch (error) {
    return usageError(deps, formatError(error));
  }

  const { values, positionals } = parsed;

  if (values.help) {
    deps.stdout(positionals[0] === 'deploy' ? JAMAL_DEPLOY_USAGE : JAMAL_USAGE);
    return 0;
  }

  if (positionals.length === 0 || positionals[0] === undefined) {
    return usageError(
      deps,
      'a subcommand is required (up | down | ps | logs | exec | dev | deploy | targets | accessory | app)',
    );
  }
  const subcommand = positionals[0];

  // `--dry-run` previews the engine plan; it is valid only for the kamal engine
  // (`deploy --target kamal`) and `rollback`.
  if (values['dry-run'] && subcommand !== 'deploy' && subcommand !== 'rollback') {
    return usageError(deps, '--dry-run is only valid for `jamal deploy` and `jamal rollback`');
  }

  // `--tag` names the image tag to deploy; it is valid only for `deploy`.
  if (values.tag !== undefined && subcommand !== 'deploy') {
    return usageError(deps, '--tag is only valid for `jamal deploy`');
  }

  // `deploy` routes by target: the kamal engine executes (or previews with
  // `--dry-run`), while every static/custom target only generates files.
  if (subcommand === 'deploy') {
    if (positionals.length > 1) {
      return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
    }
    if ((values.target ?? 'kamal') === 'kamal') {
      return runDeployCommand(deps, values);
    }
    if (values.tag !== undefined) {
      return usageError(deps, '--tag is only valid for `deploy --target kamal`');
    }
    return runPlanCommand(deps, subcommand, {
      write: values.write,
      dir: values.dir,
      target: values.target,
      dryRun: values['dry-run'],
    });
  }

  // `rollback` executes by default; `--dry-run` previews it.
  if (subcommand === 'rollback') {
    if (positionals.length > 1) {
      return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
    }
    return runRollbackCommand(deps, values);
  }

  // `status` inspects the remote server; it requires a production config.
  if (subcommand === 'status') {
    if (positionals.length > 1) {
      return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
    }
    return runRemoteStatusVerb(deps);
  }

  // `logs`/`exec` inspect the remote container when a production config is
  // present; otherwise they drive the local Compose project as before.
  if (subcommand === 'logs' || subcommand === 'exec') {
    const remote = await routeRemoteLogsOrExec(
      deps,
      subcommand,
      positionals.slice(1),
      values,
      args,
    );
    if (remote !== undefined) {
      return remote;
    }
  }

  // Execution verbs spawn `docker compose` and take their own positional
  // shape (`logs` may carry a service name); they are routed before the
  // one-positional rule that governs the generation subcommands.
  if (isDockerVerb(subcommand)) {
    return runDockerVerb(subcommand, positionals.slice(1), values, deps);
  }

  // `exec` takes a service name plus a verbatim command after `--`; it is
  // routed before the one-positional rule so the command flags stay positional.
  if (subcommand === 'exec') {
    return runDockerExec(positionals.slice(1), args.includes('--'), values, deps);
  }

  // `registry` and `audit` subcommands load the jamal config and print a plan.
  // `prune` takes --keep and --images flags. `snapshot` takes a service name
  // and optional --name/--driver; `snapshot restore` takes a snapshot path.
  // These are pure planners: they never execute Docker, resolve secrets, or
  // open a connection.

  if (subcommand === 'registry') {
    if (positionals.length > 1) {
      return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
    }
    return runRegistryCommand(deps);
  }

  if (subcommand === 'prune') {
    if (positionals.length > 1) {
      return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
    }
    return runPruneCommand(deps, values);
  }

  if (subcommand === 'audit') {
    if (positionals.length > 1) {
      return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
    }
    return runAuditCommand(deps);
  }

  if (subcommand === 'snapshot') {
    return runSnapshotCommand(deps, positionals.slice(1), values);
  }

  if (positionals.length > 1) {
    return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
  }

  if (subcommand === 'targets') {
    return runTargets(deps);
  }

  // Everything else is a generation subcommand (`dev`, `harden`): resolve the
  // generator set and plan (or write) the file set.
  return runPlanCommand(deps, subcommand, values);
}

// ---------------------------------------------------------------------------
// Registry / prune / audit / snapshot subcommand runners
// ---------------------------------------------------------------------------

/** Load the jamal config for the new planner subcommands, reporting failures. */
async function loadConfigForSubcommand(deps: JamalDeps): Promise<JamalConfig | undefined> {
  const loader = deps.loadJamalConfig ?? ((dir: string) => loadJamalConfig(dir));
  try {
    return await loader(deps.cwd);
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return undefined;
  }
}

/** `jamal registry [login]`: print the docker login argv. Never executes. */
async function runRegistryCommand(deps: JamalDeps): Promise<number> {
  const config = await loadConfigForSubcommand(deps);
  if (config === undefined) {
    return 1;
  }

  let plan: RegistryLoginPlan;
  try {
    plan = planRegistryLogin(config);
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  deps.stdout(formatRegistryLoginPlan(plan));
  return 0;
}

/** The parsed values the `jamal prune` / `jamal snapshot` commands read. */
interface ExtraPlanValues {
  readonly keep?: string;
  readonly images?: string[] | undefined;
  readonly name?: string;
  readonly snapshot?: string;
  readonly driver?: string;
}

/** `jamal prune --keep <n> [--images <ref>...]`: plan image removal. Never executes. */
async function runPruneCommand(deps: JamalDeps, values: ExtraPlanValues): Promise<number> {
  if (values.keep === undefined) {
    return usageError(deps, '--keep <n> is required for `jamal prune`');
  }
  const keep = Number(values.keep);
  if (Number.isNaN(keep) || !Number.isFinite(keep) || !Number.isInteger(keep) || keep < 1) {
    return usageError(deps, '--keep must be a positive integer >= 1');
  }

  const images: ImageRef[] = values.images ?? [];
  if (images.length === 0) {
    deps.stdout('No images to prune.');
    return 0;
  }

  let plan: ReturnType<typeof planPrune>;
  try {
    plan = planPrune({ keep, images });
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  deps.stdout(formatPrunePlan(plan));
  return 0;
}

/** `jamal audit`: print a security checklist. Never executes. */
async function runAuditCommand(deps: JamalDeps): Promise<number> {
  const config = await loadConfigForSubcommand(deps);
  if (config === undefined) {
    return 1;
  }

  const plan = planAudit(config);
  deps.stdout(formatAuditPlan(plan));
  return 0;
}

/** `jamal snapshot [restore] <service> ...`: print the dump/restore argv. Never executes. */
async function runSnapshotCommand(
  deps: JamalDeps,
  rest: readonly string[],
  values: ExtraPlanValues,
): Promise<number> {
  if (rest.length === 0) {
    return usageError(
      deps,
      'a service name is required: `jamal snapshot <service>` or `jamal snapshot restore <service> --snapshot <path>`',
    );
  }

  const verb = rest[0];
  if (verb === 'restore') {
    return runSnapshotRestoreCommand(deps, rest.slice(1), values);
  }

  // Snapshot (create): rest[0] is the service name.
  const service = verb as string;
  const driver = parseSnapshotDriver(values.driver);

  let plan: ReturnType<typeof planSnapshot>;
  try {
    plan = planSnapshot({ service, name: values.name, driver });
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  deps.stdout(formatSnapshotPlan(plan));
  return 0;
}

/** `jamal snapshot restore <service> --snapshot <path> [--driver <driver>]`. */
async function runSnapshotRestoreCommand(
  deps: JamalDeps,
  rest: readonly string[],
  values: ExtraPlanValues,
): Promise<number> {
  const service = rest[0];
  if (service === undefined || service === '') {
    return usageError(deps, 'a service name is required for `jamal snapshot restore <service>`');
  }
  if (rest.length > 1) {
    return usageError(deps, `unexpected argument: ${rest.slice(1).join(' ')}`);
  }

  if (values.snapshot === undefined || values.snapshot === '') {
    return usageError(deps, '--snapshot <path> is required for `jamal snapshot restore`');
  }

  const driver = parseSnapshotDriver(values.driver);

  let plan: ReturnType<typeof planRestore>;
  try {
    plan = planRestore({ service, snapshotPath: values.snapshot, driver });
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  deps.stdout(formatSnapshotPlan(plan));
  return 0;
}

/** Parse the --driver flag into a SnapshotDriver, defaulting to `mariadb`. */
function parseSnapshotDriver(raw: string | undefined): SnapshotDriver {
  if (raw === 'postgres') {
    return 'postgres';
  }
  return 'mariadb';
}
