/**
 * Jamal deployment command.
 *
 * Jamal wraps the deploy-generator registry behind a small, human-first CLI.
 * `jamal dev` plans the local development set (Valkey + database Docker
 * Compose); `jamal deploy` plans a production set — Kamal (the default) or a
 * static hosting target (`--target vercel|netlify|cloudflare|github`), plus any
 * custom deployment generator declared in the app config's `deployments`
 * array; `jamal targets` lists every available target without running one. By
 * default jamal only plans: it prints the files it
 * would generate, where, and the commands to run them, and writes nothing.
 * `--write` materializes the plan into the current directory (or `--dir
 * <path>`) with exclusive creation — an existing file is skipped and reported,
 * never overwritten or deleted, and missing parent directories are created.
 *
 * Custom targets are merged after the built-ins by loading `jsails.app.js`
 * (trusted app code) when it exists; a custom name that collides with a
 * built-in generator id is rejected.
 *
 * Production is the DEFAULT: `jamal deploy` plans a production set (Kamal, or
 * a static host via `--target`), while `jamal dev` is the explicit
 * local-development override. Jamal never auto-detects an environment — the
 * user names it. The Sail-like execution verbs (`up`, `down`, `ps`, `logs`)
 * drive the local Compose project generated by `dev --write` and are the one
 * place jamal spawns `docker compose`; see `src/jamal/docker.ts`. Every other
 * path (plan, `--write`, `targets`) never runs Docker, kamal, a deployment, a
 * static host, or a network call — it only generates and, with `--write`,
 * writes files. The production generators require app-specific values (service
 * name, image, hosts, project name) that this CLI surface does not collect, so
 * `deploy` plans an EXAMPLE set with placeholder values the user edits before
 * deploying.
 */

import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { parseArgs } from 'node:util';

import { DEFAULT_APP_CONFIG_PATH, loadAppConfig } from '../app/config.js';
import { BUILTIN_DEPLOYMENT_GENERATOR_IDS } from '../deploy/builtin-generators.js';
import type { KamalDatabaseOptions } from '../deploy/database-config.js';
import type { CloudflarePagesOptions } from '../deploy/hosting-config.js';
import type { KamalValkeyOptions } from '../deploy/kamal-config.js';
import {
  createDeploymentGeneratorRegistry,
  type DeploymentGenerator,
  type DeploymentGeneratorRegistry,
} from '../deploy/registry.js';
import {
  COMPOSE_FILENAME,
  composeArgv,
  defaultCommandRunner,
  isDockerVerb,
  type CommandResult,
  type CommandRunner,
  type DockerVerb,
} from './docker.js';

/** Raised for an invalid invocation or a target directory that escapes cwd. */
export class JamalError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'JamalError';
  }
}

/**
 * Placeholder production inputs. The Kamal generators require app-specific
 * values (service name, image reference, hosts, database name/user) that the
 * jamal CLI surface deliberately does not collect. These documented examples
 * match the canonical values used across the deploy test suite; the generated
 * files are marked as examples and the user edits them before deploying.
 */
const EXAMPLE_KAMAL_VALKEY_OPTIONS: KamalValkeyOptions = {
  service: 'myapp',
  image: 'ghcr.io/acme/myapp:git-sha',
  registry: { server: 'ghcr.io', username: 'acme' },
  hosts: { web: ['1.2.3.4'], worker: ['1.2.3.4'] },
  valkeyHost: '1.2.3.4',
};

const EXAMPLE_KAMAL_DATABASE_OPTIONS: KamalDatabaseOptions = {
  service: 'myapp',
  host: '1.2.3.4',
  databaseName: 'appdb',
  username: 'app',
};

/** Placeholder Cloudflare Pages project name; the user edits it before deploying. */
const EXAMPLE_CLOUDFLARE_PAGES_OPTIONS: CloudflarePagesOptions = { name: 'myapp' };

/** One jamal subcommand: the generator set it plans plus its usage hints. */
interface JamalSet {
  readonly generators: readonly string[];
  readonly hints: readonly string[];
  readonly note?: string;
}

/** Deploy target names accepted by `jamal deploy --target`. */
const DEPLOY_TARGETS = ['kamal', 'vercel', 'netlify', 'cloudflare', 'github'] as const;

/** A valid deploy target. */
type DeployTarget = (typeof DEPLOY_TARGETS)[number];

/** Generator set + usage hints per `--target` on `jamal deploy`. */
const DEPLOY_TARGET_SETS: Readonly<Record<DeployTarget, JamalSet>> = {
  kamal: {
    generators: ['valkey-kamal', 'database-kamal'],
    hints: ['kamal setup', 'kamal deploy'],
    note: 'Example values only: edit service, image, hosts, and secrets before deploying.',
  },
  vercel: {
    generators: ['vercel-static'],
    hints: ['npx vercel deploy --prod'],
    note: 'A vercel.json is generated; repos that commit a prebuilt out/ can use no-op build commands instead.',
  },
  netlify: {
    generators: ['netlify-static'],
    hints: ['npx netlify deploy --prod'],
  },
  cloudflare: {
    generators: ['cloudflare-pages'],
    hints: ['npx wrangler pages deploy out'],
    note: 'Example project name only: edit name in wrangler.toml before deploying.',
  },
  github: {
    generators: ['github-pages'],
    hints: ['git push'],
    note: 'Pushes to main deploy via the generated .github/workflows/pages.yml workflow.',
  },
};

/** One-line description per built-in deploy target (shown by `jamal targets`). */
const DEPLOY_TARGET_DESCRIPTIONS: Readonly<Record<DeployTarget, string>> = {
  kamal: 'Kamal deploy config + database accessory (Docker/Kamal containers)',
  vercel: 'Vercel static hosting (vercel.json)',
  netlify: 'Netlify static hosting (netlify.toml)',
  cloudflare: 'Cloudflare Pages static hosting (wrangler.toml)',
  github: 'GitHub Pages static workflow (.github/workflows/pages.yml)',
};

/** Subcommand -> generator ids. `deploy` resolves per `--target`; `once` is never wired. */
const JAMAL_SUBCOMMANDS: Readonly<Record<string, JamalSet>> = {
  dev: {
    generators: ['valkey-dev', 'database-dev'],
    hints: ['docker compose up -d', 'docker compose -f docker-compose.database.yml up -d'],
  },
};

/** Per-generator input; the dev generators resolve their own defaults. */
const GENERATOR_INPUT: Readonly<Record<string, unknown>> = {
  'valkey-dev': undefined,
  'database-dev': undefined,
  'valkey-kamal': EXAMPLE_KAMAL_VALKEY_OPTIONS,
  'database-kamal': EXAMPLE_KAMAL_DATABASE_OPTIONS,
  'vercel-static': undefined,
  'netlify-static': undefined,
  'cloudflare-pages': EXAMPLE_CLOUDFLARE_PAGES_OPTIONS,
  'github-pages': undefined,
};

const JAMAL_OPTIONS = {
  write: { type: 'boolean', default: false },
  dir: { type: 'string' },
  target: { type: 'string', default: 'kamal' },
  detach: { type: 'boolean', default: false },
  follow: { type: 'boolean', default: false },
  help: { type: 'boolean', short: 'h', default: false },
} as const;

const JAMAL_USAGE = `jamal - local Docker (dev) + production deployment (default)

Usage:
  jsails jamal <up|down|ps|logs|dev|deploy|targets> [options]

Production is the default: "jamal deploy" plans production (Kamal by default,
or a static host via --target), while "jamal dev" is the explicit
local-development override. Jamal never auto-detects an environment — you
always name it.

Local Docker (Sail-like) verbs — run the Compose project generated by
"jamal dev --write"; they require Docker with the compose plugin and an
existing docker-compose.yml, and never start or require other services:
  up [--detach]           docker compose up -d   (detached by default)
  down                    docker compose down
  ps                      docker compose ps
  logs [--follow] [service]
                          docker compose logs

Generation subcommands (plan only by default):
  dev      Plan the LOCAL development set (Valkey + database Docker Compose)
  deploy   Plan a PRODUCTION set (Kamal, or a static hosting target)
  targets  List the available deployment targets (built-in and custom)

Deploy targets (--target, default kamal):
  kamal       Kamal deploy config + database accessory (valkey-kamal + database-kamal)
  vercel      Vercel static hosting (vercel.json)
  netlify     Netlify static hosting (netlify.toml)
  cloudflare  Cloudflare Pages static hosting (wrangler.toml)
  github      GitHub Pages static workflow (.github/workflows/pages.yml)

  Once written, deploy the target with:
    kamal       ->  kamal setup && kamal deploy
    vercel      ->  npx vercel deploy --prod
    netlify     ->  npx netlify deploy --prod
    cloudflare  ->  npx wrangler pages deploy out
    github      ->  git push  (the generated workflow builds and deploys)

Custom targets come from the \`deployments\` array in jsails.app.js. Run
"jsails jamal targets" to list them.

Options:
  --target <name>  Deploy target (deploy only): kamal | vercel | netlify |
                   cloudflare | github (plus any custom deployment name)
  --write          Write the generated files (dev/deploy; never overwrites)
  --dir <path>     Directory for the plan, or the Compose project root (up/
                   down/ps/logs) instead of the current directory
  --detach         Accepted for \`up\`; already the default (up always detaches)
  --follow         Follow logs instead of a one-shot dump (logs only)
  -h, --help       Show this help

By default jamal dev/deploy only plan: they print the files they would generate
and write nothing. Pass --write to materialize them. Generation never runs
Docker, kamal, a static host, or a deployment; only the up/down/ps/logs verbs
spawn docker compose, and only against the local project.
`;

const JAMAL_DEPLOY_USAGE = `jamal deploy - plan production deployment files (plan only by default)

Usage:
  jsails jamal deploy [--target <name>] [options]

Production is the default: deploy plans a production set (Kamal by default).
Use "jamal dev" for the explicit local-development override; jamal never
auto-detects an environment.

Deploy targets (--target, default kamal):
  kamal       Kamal deploy config + database accessory (valkey-kamal + database-kamal)
  vercel      Vercel static hosting (vercel.json)
  netlify     Netlify static hosting (netlify.toml)
  cloudflare  Cloudflare Pages static hosting (wrangler.toml)
  github      GitHub Pages static workflow (.github/workflows/pages.yml)

  Once written, deploy the target with:
    kamal       ->  kamal setup && kamal deploy
    vercel      ->  npx vercel deploy --prod
    netlify     ->  npx netlify deploy --prod
    cloudflare  ->  npx wrangler pages deploy out
    github      ->  git push  (the generated workflow builds and deploys)

Custom targets come from the \`deployments\` array in jsails.app.js: each entry
is a deployment generator with a name and a generate(input, context?) function
that returns { files } without writing or deploying. Run "jsails jamal targets"
to list the custom targets loaded from the config.

Options:
  --target <name>  Deploy target: a built-in target above, or a custom
                   deployment name from jsails.app.js
  --write          Write the generated files (exclusive create; never overwrites)
  --dir <path>     Write into <path> instead of the current directory
  -h, --help       Show this help

By default jamal deploy only plans: it prints the files it would generate and
writes nothing. Pass --write to materialize them. Jamal never runs Docker,
kamal, a static host, or a deployment.
`;

/**
 * Dependency seam for the jamal command. Tests inject a stub registry and
 * captured output sinks so no generator runs and nothing touches disk; the
 * defaults are the real built-in registry and the process's stdout/stderr.
 */
export interface JamalDeps {
  /**
   * Build the deploy-generator registry used to plan the file set, seeded with
   * the built-in generators plus any custom deployments from the app config.
   */
  createRegistry(custom?: readonly DeploymentGenerator<unknown>[]): DeploymentGeneratorRegistry;
  /**
   * Load the app config's custom deployment generators (trusted app code).
   * Resolves `undefined` when no `jsails.app.js` config is present and an array
   * (possibly empty) when a config was loaded. Absent in a test seam, the
   * command treats it as "no config".
   */
  loadDeployments?(cwd: string): Promise<readonly DeploymentGenerator<unknown>[] | undefined>;
  /** Working directory the target directory resolves against. */
  readonly cwd: string;
  stdout(text: string): void;
  stderr(text: string): void;
  /**
   * Spawn a fixed argv array with a given working directory. Injected for the
   * execution verbs (`up`/`down`/`ps`/`logs`) so tests never spawn a real
   * process; defaults to the streaming `docker compose` runner. Absent in a
   * test seam, an execution verb reports "docker compose is unavailable".
   */
  runCommand?: CommandRunner;
}

export const defaultJamalDeps: JamalDeps = {
  createRegistry: (custom = []) => createDeploymentGeneratorRegistry({ generators: custom }),
  loadDeployments: (cwd) => loadCustomDeployments(cwd),
  cwd: process.cwd(),
  stdout: (text) => process.stdout.write(`${text}\n`),
  stderr: (text) => process.stderr.write(`${text}\n`),
  runCommand: defaultCommandRunner,
};

/**
 * Load the app config's custom deployments, when a `jsails.app.js` module is
 * present in `cwd`. The config module is trusted app code and is imported for
 * its side effects, exactly as `serve`/`build` do; a missing config returns
 * `undefined` so `jamal targets` can report the absence rather than an error.
 */
async function loadCustomDeployments(
  cwd: string,
): Promise<readonly DeploymentGenerator<unknown>[] | undefined> {
  const configPath = resolve(cwd, DEFAULT_APP_CONFIG_PATH);
  if (!existsSync(configPath)) {
    return undefined;
  }
  const resolved = await loadAppConfig(configPath);
  return resolved.deployments;
}

/** Built-in generator ids are reserved: a custom deployment may not reuse one. */
const RESERVED_GENERATOR_IDS: ReadonlySet<string> = new Set(BUILTIN_DEPLOYMENT_GENERATOR_IDS);

/** Reject a custom deployment whose name collides with a built-in generator id. */
function assertNoBuiltinCollisions(deployments: readonly DeploymentGenerator<unknown>[]): void {
  for (const generator of deployments) {
    if (RESERVED_GENERATOR_IDS.has(generator.name)) {
      throw new JamalError(
        `custom deployment "${generator.name}" collides with a built-in deployment generator name`,
      );
    }
  }
}

function formatError(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

function isNodeError(error: unknown, code: string): boolean {
  return (
    error instanceof Error && 'code' in error && (error as NodeJS.ErrnoException).code === code
  );
}

/** Print a usage failure to stderr and return the exit code (2). */
function usageError(deps: JamalDeps, message: string): number {
  deps.stderr(`jsails: ${message}`);
  deps.stderr('Run "jsails jamal --help" for usage.');
  return 2;
}

/**
 * Resolve the target directory from `--dir` (defaulting to `cwd`) and reject a
 * path that escapes the working directory. `..` traversal, an absolute path
 * that lands elsewhere, and any resolution outside `cwd` are refused.
 */
function resolveTargetDir(cwd: string, dir: string | undefined): string {
  const base = resolve(cwd);
  if (dir === undefined || dir === '') {
    return base;
  }
  const target = resolve(base, dir);
  const rel = relative(base, target);
  if (rel !== '' && (rel === '..' || rel.startsWith(`..${sep}`) || isAbsolute(rel))) {
    throw new JamalError(
      `--dir ${JSON.stringify(dir)} escapes the working directory; choose a path inside it`,
    );
  }
  return target;
}

/** Plan one entry: relative path plus contents. */
type PlannedFile = readonly [string, string];

/**
 * Run every generator in the set and merge their file maps into one
 * deterministic (sorted) plan. A path emitted by two generators is a hard
 * error rather than a silent overwrite.
 */
async function planFiles(
  registry: DeploymentGeneratorRegistry,
  generatorIds: readonly string[],
): Promise<PlannedFile[]> {
  const files = new Map<string, string>();
  for (const id of generatorIds) {
    const result = await registry.generate(id, GENERATOR_INPUT[id]);
    for (const [path, content] of Object.entries(result.files)) {
      if (files.has(path)) {
        throw new JamalError(`generated file "${path}" is produced by more than one generator`);
      }
      files.set(path, content);
    }
  }
  return [...files.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
}

/** Outcome of a `--write`: every file either written or skipped (never both). */
interface JamalWriteResult {
  readonly written: readonly string[];
  readonly skipped: readonly string[];
  readonly error?: string;
}

/**
 * Materialize the plan into `targetDir` with exclusive creation. Missing parent
 * directories are created first; an `EEXIST` on the file is reported as a skip
 * (never overwritten), while any other failure aborts the run with an error.
 */
async function writeFiles(
  targetDir: string,
  planned: readonly PlannedFile[],
): Promise<JamalWriteResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  for (const [rel, content] of planned) {
    const dest = join(targetDir, ...rel.split('/'));
    try {
      await mkdir(dirname(dest), { recursive: true });
    } catch (error) {
      return {
        written,
        skipped,
        error: `could not create the parent directory for "${rel}": ${formatError(error)}`,
      };
    }
    try {
      await writeFile(dest, content, { flag: 'wx' });
      written.push(rel);
    } catch (error) {
      if (isNodeError(error, 'EEXIST')) {
        skipped.push(rel);
        continue;
      }
      return { written, skipped, error: `could not write "${rel}": ${formatError(error)}` };
    }
  }
  return { written, skipped };
}

/** Print the dry-run plan: what, where, and how to use it. Writes nothing. */
function printPlan(
  stdout: (text: string) => void,
  commandLabel: string,
  set: JamalSet,
  planned: readonly PlannedFile[],
  targetDir: string,
  writeCommand: string,
): void {
  stdout(
    `jamal ${commandLabel} - ${planned.length} file(s) planned into ${targetDir} (nothing written).`,
  );
  stdout('');
  for (const [rel] of planned) {
    stdout(`  ${rel}`);
  }
  stdout('');
  stdout(`To write these files, run: ${writeCommand}`);
  stdout('');
  stdout('Next steps:');
  for (const hint of set.hints) {
    stdout(`  ${hint}`);
  }
  if (set.note !== undefined) {
    stdout(`  ${set.note}`);
  }
}

/** Print the write result: written vs skipped, then the usage hints. */
function printWriteResult(
  stdout: (text: string) => void,
  commandLabel: string,
  set: JamalSet,
  result: JamalWriteResult,
): void {
  stdout(
    `jamal ${commandLabel} - wrote ${result.written.length} file(s), skipped ${result.skipped.length}.`,
  );
  for (const rel of result.written) {
    stdout(`  wrote    ${rel}`);
  }
  for (const rel of result.skipped) {
    stdout(`  skipped  ${rel} (already exists)`);
  }
  if (result.written.length > 0) {
    stdout('');
    stdout('Next steps:');
    for (const hint of set.hints) {
      stdout(`  ${hint}`);
    }
    if (set.note !== undefined) {
      stdout(`  ${set.note}`);
    }
  }
}

/**
 * Resolve a deploy target name to its generator set. Built-in aliases win
 * first; a custom deployment name matches second; anything else is `undefined`.
 */
function resolveDeployTarget(
  target: string,
  custom: readonly DeploymentGenerator<unknown>[],
): JamalSet | undefined {
  const builtin = DEPLOY_TARGET_SETS[target as DeployTarget];
  if (builtin !== undefined) {
    return builtin;
  }
  if (custom.some((generator) => generator.name === target)) {
    return {
      generators: [target],
      hints: [],
      note: 'Custom deployment target from the deployments array in jsails.app.js; deploy it with your own tooling.',
    };
  }
  return undefined;
}

/** Deploy target names, built-in aliases first then custom names, for errors. */
function listDeployTargets(custom: readonly DeploymentGenerator<unknown>[]): string[] {
  return [...DEPLOY_TARGETS, ...custom.map((generator) => generator.name)];
}

/** Custom deployments loaded from the app config plus whether a config exists. */
interface LoadedDeployments {
  readonly deployments: readonly DeploymentGenerator<unknown>[];
  readonly hasConfig: boolean;
}

/**
 * Load custom deployments from the app config and reject a name that collides
 * with a built-in generator id. `hasConfig` is `false` only when no
 * `jsails.app.js` module is present (the seam resolved `undefined`).
 */
async function loadDeployments(deps: JamalDeps): Promise<LoadedDeployments> {
  const loaded =
    deps.loadDeployments === undefined ? undefined : await deps.loadDeployments(deps.cwd);
  if (loaded === undefined) {
    return { deployments: [], hasConfig: false };
  }
  assertNoBuiltinCollisions(loaded);
  return { deployments: loaded, hasConfig: true };
}

/** Print the `jamal targets` listing. Never runs a generator. */
function printTargets(stdout: (text: string) => void, loaded: LoadedDeployments): void {
  stdout('Built-in deployment targets:');
  for (const target of DEPLOY_TARGETS) {
    stdout(`  ${target.padEnd(12)}${DEPLOY_TARGET_DESCRIPTIONS[target]}`);
  }
  stdout('');
  if (loaded.deployments.length === 0) {
    stdout(
      loaded.hasConfig
        ? 'No custom deployment targets declared in jsails.app.js.'
        : 'No custom deployment targets (no jsails.app.js config present).',
    );
    return;
  }
  stdout('Custom deployment targets (from jsails.app.js):');
  for (const generator of loaded.deployments) {
    stdout(`  ${generator.name}`);
  }
}

/** `jamal targets`: list built-in and custom targets without running a generator. */
async function runTargets(deps: JamalDeps): Promise<number> {
  let loaded: LoadedDeployments;
  try {
    loaded = await loadDeployments(deps);
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }
  printTargets(deps.stdout, loaded);
  return 0;
}

/**
 * Run one execution verb (`up`/`down`/`ps`/`logs`) against the local Compose
 * project. This is the one place jamal spawns a process: it requires the
 * compose file generated by `jamal dev --write` and a Docker CLI with the
 * compose plugin, then forwards the child's exit code. It never builds the
 * registry, never runs a generator, and never starts other services.
 */
async function runDockerVerb(
  verb: DockerVerb,
  rest: readonly string[],
  values: { readonly dir?: string; readonly follow: boolean },
  deps: JamalDeps,
): Promise<number> {
  if (verb !== 'logs' && rest.length > 0) {
    return usageError(deps, `"jamal ${verb}" takes no arguments`);
  }
  if (verb === 'logs' && rest.length > 1) {
    return usageError(deps, `"jamal logs" takes at most one service name; got: ${rest.join(' ')}`);
  }

  let targetDir: string;
  try {
    targetDir = resolveTargetDir(deps.cwd, values.dir);
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  if (!existsSync(join(targetDir, COMPOSE_FILENAME))) {
    deps.stderr(
      `jsails: no ${COMPOSE_FILENAME} found in ${targetDir}; run "jsails jamal dev --write" to generate it first`,
    );
    return 1;
  }

  if (deps.runCommand === undefined) {
    deps.stderr('jsails: docker compose is not available in this environment');
    return 127;
  }

  const argv = composeArgv(verb, {
    follow: values.follow,
    service: verb === 'logs' ? rest[0] : undefined,
  });

  let result: CommandResult;
  try {
    result = await deps.runCommand(argv, { cwd: targetDir });
  } catch (error) {
    if (isNodeError(error, 'ENOENT')) {
      deps.stderr(
        'jsails: docker compose is not available; install Docker with the compose plugin and ensure "docker" is on PATH',
      );
      return 127;
    }
    deps.stderr(`jsails: failed to run docker compose ${verb}: ${formatError(error)}`);
    return 1;
  }

  if (result.stdout !== '') {
    deps.stdout(result.stdout.replace(/\n$/, ''));
  }
  if (result.stderr !== '') {
    deps.stderr(result.stderr.replace(/\n$/, ''));
  }
  if (result.exitCode !== 0) {
    deps.stderr(`jsails: docker compose ${verb} exited with code ${result.exitCode}`);
  }
  return result.exitCode;
}

/**
 * Run the `jamal` command over the tokens after the `jamal` command name.
 * Resolves to a process exit code: 0 on success (including a dry run, a
 * `targets` listing, a run where files were skipped, and a clean `docker
 * compose` execution), 2 for usage errors, 1 for a generation/write failure
 * or a spawn failure, 127 when docker compose is unavailable, and the child's
 * own exit code when a compose verb fails. Help and usage paths never build
 * the registry, run a generator, or spawn a process.
 */
export async function runJamalCommand(
  args: readonly string[],
  deps: JamalDeps = defaultJamalDeps,
): Promise<number> {
  let parsed;
  try {
    parsed = parseArgs({
      args: [...args],
      options: JAMAL_OPTIONS,
      allowPositionals: true,
      strict: true,
    });
  } catch (error) {
    return usageError(deps, formatError(error));
  }

  const { values, positionals } = parsed;

  if (values.help) {
    deps.stdout(positionals[0] === 'deploy' ? JAMAL_DEPLOY_USAGE : JAMAL_USAGE);
    return 0;
  }

  if (positionals.length === 0 || positionals[0] === undefined) {
    return usageError(
      deps,
      'a subcommand is required (up | down | ps | logs | dev | deploy | targets)',
    );
  }
  const subcommand = positionals[0];

  // Execution verbs spawn `docker compose` and take their own positional
  // shape (`logs` may carry a service name); they are routed before the
  // one-positional rule that governs the generation subcommands.
  if (isDockerVerb(subcommand)) {
    return runDockerVerb(subcommand, positionals.slice(1), values, deps);
  }

  if (positionals.length > 1) {
    return usageError(deps, `unexpected argument: ${positionals.slice(1).join(' ')}`);
  }

  if (subcommand === 'targets') {
    return runTargets(deps);
  }

  // `deploy` resolves its generator set from `--target` (built-in aliases
  // first, then custom deployment names); `dev` has a fixed set.
  let set: JamalSet;
  let commandLabel: string;
  let writeCommand: string;
  let registry: DeploymentGeneratorRegistry;
  if (subcommand === 'deploy') {
    let deployments: readonly DeploymentGenerator<unknown>[];
    try {
      deployments = (await loadDeployments(deps)).deployments;
    } catch (error) {
      deps.stderr(`jsails: ${formatError(error)}`);
      return 1;
    }
    const target = values.target ?? 'kamal';
    const resolved = resolveDeployTarget(target, deployments);
    if (resolved === undefined) {
      return usageError(
        deps,
        `unknown --target ${JSON.stringify(target)}; available targets: ${listDeployTargets(deployments).join(', ')}`,
      );
    }
    set = resolved;
    commandLabel = `deploy --target ${target}`;
    writeCommand = `jsails jamal deploy --target ${target} --write`;
    registry = deps.createRegistry(deployments);
  } else {
    const devSet = JAMAL_SUBCOMMANDS[subcommand];
    if (devSet === undefined) {
      return usageError(deps, `unknown subcommand ${JSON.stringify(subcommand)}`);
    }
    set = devSet;
    commandLabel = subcommand;
    writeCommand = `jsails jamal ${subcommand} --write`;
    registry = deps.createRegistry([]);
  }

  let targetDir: string;
  try {
    targetDir = resolveTargetDir(deps.cwd, values.dir);
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  let planned: PlannedFile[];
  try {
    planned = await planFiles(registry, set.generators);
  } catch (error) {
    deps.stderr(`jsails: ${formatError(error)}`);
    return 1;
  }

  if (!values.write) {
    printPlan(deps.stdout, commandLabel, set, planned, targetDir, writeCommand);
    return 0;
  }

  const result = await writeFiles(targetDir, planned);
  printWriteResult(deps.stdout, commandLabel, set, result);
  if (result.error !== undefined) {
    deps.stderr(`jsails: ${result.error}`);
    return 1;
  }
  return 0;
}
