/**
 * Help and usage text for the jamal command.
 *
 * Kept separate from control flow so the text can be reviewed and edited
 * without touching command logic. Every string is emitted verbatim and never
 * influences behavior.
 */

export const JAMAL_USAGE = `jamal - local Docker (dev) + production deployment (default)

Usage:
    jsails jamal <up|down|ps|logs|exec|status|dev|deploy|rollback|harden|targets|domain|registry|prune|audit|snapshot|accessory|app> [options]

Production is the default: "jamal deploy" runs a production release (Kamal, the
Docker/SSH engine, by default) while "jamal dev" is the explicit
local-development override. Jamal never auto-detects an environment — you
always name it.

Local Docker (Sail-like) verbs — require Docker with the compose plugin and
never start or require other services:
  up [--detach]           materialize .jamal/compose.yml from jamal.config.js,
                          then docker compose up -d --wait
                          (detached and health-waited by default)
  down                    docker compose down
  ps                      docker compose ps
  logs [--follow] [service]
                          docker compose logs
  exec <service> -- <cmd...>
                          docker compose exec <service> -- <cmd...>
                          (managed .jamal/compose.yml only)

down/ps/logs use the managed .jamal/compose.yml and its project when that file
exists, and otherwise fall back to the legacy docker-compose.yml generated by
"jamal dev --write". exec always requires the managed file.

Production execution verbs (require config.production; see below):
  deploy [--tag <tag>] [--dry-run]
                          Perform a real production deploy: build and push the
                          image locally, then pull, run, health-check, switch,
                          and stop the previous container on the remote server.
                          The deployed tag is recorded in .jamal/deploys.json.
                          Pass --dry-run to print the plan and run nothing.
  rollback [--dry-run]    Deploy the previous successful tag (from
                          .jamal/deploys.json) and stop the current container.
                          Pass --dry-run to print the plan and run nothing.
  status                  List containers on the remote server (docker ps)
  logs [--follow]         Follow (or dump) the logs of the last deployed
                          container on the remote server
  exec -- <cmd...>        Run <cmd...> inside the last deployed container on
                          the remote server (requires "--" before the command)
registry login        Print the docker login argv for the production registry.
                           The password is a secret() reference; resolve it
                           before running the command. Requires
                           config.production.registry.
  prune --keep <n> [--images <ref>...]
                           Plan which images to remove, keeping the <n> most
                           recent per service. Images must be passed explicitly
                           (e.g. from "docker image ls" output, newest first).
  audit                 Print a security checklist for the jamal config.
  snapshot <service> [--name <name>] [--driver mariadb|postgres]
                           Print a "docker compose exec" argv for a database
                           dump (snapshot) inside the named service container.
  snapshot restore <service> [--snapshot <path>] [--driver mariadb|postgres]
                           Print a "docker compose exec" argv to restore a
                           database snapshot into the named service container.
  domain <add|list|remove>
                           Manage the proxy's public domains (add <host> routes
                           a host to the latest deploy; list dumps the proxy
                           routing table; remove <host> removes the service).
See "jsails jamal domain --help".

    accessory <boot|start|stop|reboot|logs|remove|details> [name] [--follow] [--dry-run]
                           Manage backing service containers (mariadb, postgres,
                           valkey) on the remote production server. Requires
                           config.production. See "jsails jamal accessory --help".

  app <boot|start|stop|details|containers|logs|exec>
                           Manage the app container on the remote production
                           server. Requires config.production. Every verb targets
                           the LATEST recorded deploy. See "jsails jamal app --help".

  When a config.production section is present, "jamal logs" and "jamal exec"
inspect the remote container instead of the local Compose project.

Generation subcommands:
  dev      Plan the LOCAL development set (Valkey + database Docker Compose)
  deploy   (static/custom targets only) Generate the target's deploy files;
           requires --write. Kamal is the engine, not a file generator.
  harden   Plan the server-hardening script (config/harden-server.sh, UFW)
  targets  List the available deployment targets (built-in and custom)

Deploy targets (--target, default kamal):
  kamal       Docker/SSH engine release (executes by default; --dry-run previews)
  vercel      Vercel static hosting (vercel.json)
  netlify     Netlify static hosting (netlify.toml)
  cloudflare  Cloudflare Pages static hosting (wrangler.toml)
  github      GitHub Pages static workflow (.github/workflows/pages.yml)

  The kamal engine executes the release itself. Static targets generate files
  (require --write) that you deploy with the host's own CLI:
    vercel      ->  npx vercel deploy --prod
    netlify     ->  npx netlify deploy --prod
    cloudflare  ->  npx wrangler pages deploy out
    github      ->  git push  (the generated workflow builds and deploys)

Custom targets come from the \`deployments\` array in jsails.app.js. Run
"jsails jamal targets" to list them.

Options:
  --target <name>  Deploy target (deploy only): kamal | vercel | netlify |
                   cloudflare | github (plus any custom deployment name)
  --dry-run        Print the production plan (deploy/rollback) and run nothing
  --write          Write the generated files (dev/harden/deploy static targets;
                   never overwrites)
  --dir <path>     Directory for the plan, or the Compose project root (up/
                   down/ps/logs/exec) instead of the current directory
  --detach         Accepted for \`up\`; already the default (up always detaches)
  --follow         Follow logs instead of a one-shot dump (logs only)
  --tag <tag>      Image tag to deploy (deploy only; defaults to
                   "git rev-parse --short HEAD", falling back to a timestamp)
  -h, --help       Show this help

"jamal deploy" and "jamal rollback" execute the production release by default;
pass --dry-run to preview the plan. "jamal dev"/"jamal harden" plan by default
and write nothing until you pass --write; a static/custom deploy target requires
--write and is never deployed by jamal. The up/down/ps/logs/exec verbs spawn
docker compose against the local project, and deploy/rollback plus
status/logs/exec (with config.production) drive the remote release engine.
`;

export const JAMAL_DEPLOY_USAGE = `jamal deploy - run a production release (kamal) or generate deploy files

Usage:
  jsails jamal deploy [--target <name>] [options]

Production is the default. With --target kamal (the default) deploy EXECUTES a
real production release: it builds and pushes the image locally, then pulls,
runs, health-checks, switches, and stops the previous container on the remote
server, recording the tag in .jamal/deploys.json. Pass --dry-run to print the
plan and run nothing.

A static or custom target generates files only (jamal never deploys them):
  kamal       Docker/SSH engine release (executes by default)
  vercel      Vercel static hosting (vercel.json)
  netlify     Netlify static hosting (netlify.toml)
  cloudflare  Cloudflare Pages static hosting (wrangler.toml)
  github      GitHub Pages static workflow (.github/workflows/pages.yml)

  Static targets require --write and are deployed with the host's own CLI:
    vercel      ->  npx vercel deploy --prod
    netlify     ->  npx netlify deploy --prod
    cloudflare  ->  npx wrangler pages deploy out
    github      ->  git push  (the generated workflow builds and deploys)

Custom targets come from the \`deployments\` array in jsails.app.js: each entry
is a deployment generator with a name and a generate(input, context?) function
that returns { files } without writing or deploying. Run "jsails jamal targets"
to list the custom targets loaded from the config.

Options:
  --target <name>  Deploy target: a built-in target above, or a custom
                   deployment name from jsails.app.js
  --dry-run        Print the production plan and run nothing (kamal only)
  --write          Write the generated files (static/custom targets; exclusive
                   create, never overwrites)
  --dir <path>     Write into <path> instead of the current directory
  --tag <tag>      Image tag to deploy (kamal only; defaults to
                   "git rev-parse --short HEAD", falling back to a timestamp)
  -h, --help       Show this help

"jamal deploy --target kamal" executes by default; --dry-run previews it. A
built-in static target (vercel/netlify/cloudflare) generates its config, requires
--write, then executes the deploy through npx; github is push-based (workflow +
"git push"). A custom deployment only generates files and never deploys.
`;

export const DOMAIN_USAGE = `jamal domain - manage the proxy's public domains

Usage:
  jsails jamal domain <add|list|remove> [options]

Production only: "jamal domain" requires config.production (the remote server)
and resolves the backend service from --service (or config.service). Every verb
drives the running kamal-proxy container over ssh.

Subcommands:
  add <host>    Route <host> to the LATEST deployed container, terminating TLS
                at the proxy by default. The backend target is reconstructed
                from .jamal/deploys.json, so a production deploy must already
                be recorded.
  list          Dump the proxy's routing table on the remote server.
  remove <host> Remove the service (and its routed host) from the proxy. The
                proxy removes by service, so <host> names the domain but the
                operation is service-scoped.

Notes:
  These verbs drive the proxy's runtime deploy/remove API over ssh, not a config
  file: a host added here is NOT recorded in deploy.yml, so a later external
  "kamal deploy" may overwrite or conflict with it. Use on-demand TLS for
  unknown/customer hosts, and note that --tls static hosts and on-demand TLS are
  mutually exclusive.

Options:
  --service <name>  Backend service name (defaults to config.service)
  --no-tls          (add only) Do not terminate TLS at the proxy
  --dry-run         Print the exact ssh command without running it
  -h, --help        Show this help
`;

export const ACCESSORY_USAGE = `jamal accessory - manage backing service containers on the remote server

Usage:
  jsails jamal accessory <boot|start|stop|reboot|logs|remove|details> [name] [options]

Production only: "jamal accessory" requires config.production (the remote server).
Every verb drives docker commands over ssh on the target server.

Verbs:
  boot [name]    Create the data volume (idempotent) and start the container
                 if it is not already running. With no name, boot every backing
                 service (mariadb, postgres, valkey).
  start [name]   Start an existing stopped container. No name -> all.
  stop [name]    Stop a running container. No name -> all.
  reboot [name]  Restart a container. No name -> all.
  logs <name> [--follow]
                 Show (or follow) the logs of one accessory container. Requires
                 a name (a single service; no "all" mode).
  remove [name]  Stop and remove a container (the data volume is left intact).
                 No name -> all.
  details <name> Show the docker inspect JSON for one accessory container.
                 Requires a name.

Options:
  --follow        Follow logs instead of a one-shot dump (logs only)
  --dry-run       Print the exact ssh command(s) without running them
  -h, --help      Show this help
`;

export const APP_USAGE = `jamal app - manage the app container on the remote server

Usage:
  jsails jamal app <boot|start|stop|details|containers|logs|exec> [options]

Production only: "jamal app" requires config.production (the remote server).
Every verb targets the LATEST recorded deploy container, reconstructed from
.jamal/deploys.json (a production deploy must already be recorded).

Verbs:
  boot            Start the app container if it is not already running.
  start           Start the latest deployed container.
  stop            Stop the latest deployed container.
  details         Show docker inspect JSON for the latest deployed container.
  containers      List the app's containers on the server (filtered by service name).
  logs [--follow] Show (or follow) the logs of the latest deployed container.
  exec -- <cmd...>
                  Run <cmd...> inside the latest deployed container.
                  Requires "--" before the command.

Options:
  --follow        Follow logs instead of a one-shot dump (logs only)
  --dry-run       Print the exact ssh command without running it
  -h, --help      Show this help
`;
