/**
 * Server hardening script generator (UFW).
 *
 * {@link generateServerHardeningConfig} produces a single shell script as a
 * string — `config/harden-server.sh` — in the same family as the Valkey,
 * database, Kamal, ONCE, and static-hosting generators: it is pure, never
 * writes files, never runs `ufw` or any command, never opens a connection, and
 * never embeds a secret. Writing the returned string to disk and running it is
 * the caller's (a human's) responsibility.
 *
 * The script is deliberately conservative and idempotent:
 * - it refuses to run when `ufw` is not installed (`command -v ufw` guard);
 * - it only enables the firewall when `ufw status` reports it inactive;
 * - it applies a default-deny-incoming / default-allow-outgoing policy, allows
 *   OpenSSH, 80, and 443, then enables UFW;
 * - its comments document the rollback (`ufw disable`), the requirement to
 *   allow a non-22 SSH port first, and that Docker-published ports bypass UFW
 *   (they need a DOCKER-USER chain rule);
 * - disabling SSH password auth and installing fail2ban are documented as
 *   commented suggestions only, never auto-applied.
 */

import { assertPlainOptions as validatePlainOptions } from './validators.js';

/** Generated hardening script path (relative to the app/project root). */
export const HARDENING_SCRIPT_FILENAME = 'config/harden-server.sh';

/** Raised for any invalid hardening option. Messages never embed input. */
export class HardeningConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'HardeningConfigError';
  }
}

/** Options for {@link generateServerHardeningConfig}. Reserved; currently empty. */
export interface ServerHardeningOptions {}

/** Generated server-hardening files as strings. */
export interface ServerHardeningFiles {
  /** `config/harden-server.sh` content: idempotent UFW hardening with review notes. */
  script: string;
}

/** Reject a non-plain-object options argument. */
function assertPlainOptions(options: unknown, label: string): void {
  validatePlainOptions(options, label, HardeningConfigError);
}

function buildScript(): string {
  return [
    '#!/bin/sh',
    '# JSails server hardening (generated by generateServerHardeningConfig).',
    '#',
    '# Jamal never runs this script: review it, then run it by hand.',
    '#   sudo sh config/harden-server.sh',
    '#',
    '# Idempotent: safe to re-run. Rules are only added when missing and the',
    '# firewall is only enabled when it is not already active.',
    'set -eu',
    '',
    '# Rollback: `sudo ufw disable` turns the firewall back off. If you lock',
    '# yourself out, run it from the host console.',
    '',
    '# Require ufw: fail loudly instead of silently skipping hardening.',
    'if ! command -v ufw >/dev/null 2>&1; then',
    '  echo "ufw is not installed; install it first (e.g. apt-get install ufw)" >&2',
    '  exit 1',
    'fi',
    '',
    '# Default policy: deny everything inbound, allow everything outbound.',
    'ufw default deny incoming',
    'ufw default allow outgoing',
    '',
    '# Allow the ports the server actually serves.',
    '#',
    '# SSH first. If you run SSH on a non-22 port, allow that port HERE before',
    '# enabling the firewall below, or you will be locked out.',
    'ufw allow OpenSSH',
    '# HTTP / HTTPS for the app (kamal-proxy serves 80/443).',
    'ufw allow 80/tcp',
    'ufw allow 443/tcp',
    '',
    '# Enable the firewall only when it is not already active (idempotent).',
    "if ! ufw status | grep -q '^Status: active'; then",
    '  ufw --force enable',
    'fi',
    '',
    '# NOTE: Docker-published ports bypass UFW. Docker inserts its own rules into',
    "# the FORWARD chain, which UFW's default rules do not govern; to make UFW",
    '# apply to ports published with `docker run -p`, restrict the DOCKER-USER',
    "# chain (which Docker inserts before UFW's FORWARD rules). See the",
    '# ufw-docker documentation for the recommended rules.',
    '',
    '# Suggested, NOT applied automatically. Review and run by hand:',
    '#   - Disable SSH password authentication (key-only): in /etc/ssh/sshd_config',
    '#     set "PasswordAuthentication no" and "PermitRootLogin prohibit-password",',
    '#     then restart sshd.',
    '#   - Install fail2ban to block repeated authentication failures:',
    '#       apt-get install fail2ban',
    '#     and enable the sshd jail in /etc/fail2ban/jail.local.',
    '',
  ].join('\n');
}

/**
 * Generate the server-hardening script: a `config/harden-server.sh` that
 * applies a default-deny UFW policy for OpenSSH, 80, and 443. Returns a string
 * only; nothing is written to disk or run, and no secret is embedded.
 */
export function generateServerHardeningConfig(
  options: ServerHardeningOptions = {},
): ServerHardeningFiles {
  assertPlainOptions(options, 'options');
  return { script: buildScript() };
}
