/**
 * Static-hosting configuration generators.
 *
 * These functions produce configuration FILES as strings for deploying a
 * JSails static export (`out/`) to common static hostings — Vercel, Netlify,
 * Cloudflare Pages, and GitHub Pages — instead of the container/Kamal path.
 * They are pure string generators in the same family as the Valkey/database/
 * Kamal/ONCE generators: they never write files, never run `vercel`,
 * `netlify`, `wrangler`, `git`, or any deployment, never open a connection,
 * and never embed a secret. Writing the returned strings to disk is the
 * caller's responsibility.
 *
 * Each target assumes `npm run build` compiles the app and statically exports
 * it into `out/`. The Vercel config uses the real build/install commands; for
 * a repo that commits a prebuilt `out/` directory, the no-op alternative is to
 * set `buildCommand`/`installCommand` to `null` (or use Vercel's "Other"
 * framework preset, which performs no build at all) — documented here, not
 * emitted, because the default scaffolds build on demand.
 */

/** Vercel's published `vercel.json` JSON Schema id. */
export const VERCEL_CONFIG_SCHEMA = 'https://openapi.vercel.sh/vercel.json';

/** Maximum length of a Cloudflare Pages project name. */
export const CLOUDFLARE_PAGES_NAME_MAX_LENGTH = 58;

/** Raised for any invalid hosting config option. Messages never embed input. */
export class HostingConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'HostingConfigError';
  }
}

/** Options for {@link generateVercelStaticConfig}. Reserved; currently empty. */
export interface VercelStaticOptions {}

/** Generated Vercel files as strings. */
export interface VercelStaticFiles {
  /** `vercel.json` content: static export with clean URLs and no trailing slash. */
  vercelJson: string;
}

/** Options for {@link generateNetlifyStaticConfig}. Reserved; currently empty. */
export interface NetlifyStaticOptions {}

/** Generated Netlify files as strings. */
export interface NetlifyStaticFiles {
  /** `netlify.toml` content: build publishes `out/` with pretty URLs. */
  netlifyToml: string;
}

/** Options for {@link generateCloudflarePagesConfig}. */
export interface CloudflarePagesOptions {
  /** Cloudflare Pages project name (lowercase letters, digits, hyphens). */
  name: string;
}

/** Generated Cloudflare Pages files as strings. */
export interface CloudflarePagesFiles {
  /** `wrangler.toml` content: project name plus the static output directory. */
  wranglerToml: string;
}

/** Options for {@link generateGitHubPagesConfig}. Reserved; currently empty. */
export interface GitHubPagesOptions {}

/** Generated GitHub Pages files as strings. */
export interface GitHubPagesFiles {
  /** `.github/workflows/pages.yml` content: the official static Pages workflow. */
  workflow: string;
  /** `.nojekyll` placeholder (empty marker; disables GitHub's Jekyll build). */
  nojekyll: string;
}

/**
 * Cloudflare Pages project name: lowercase letters/digits/hyphens, never a
 * leading or trailing hyphen. Length is bounded separately by
 * {@link CLOUDFLARE_PAGES_NAME_MAX_LENGTH}.
 */
const CLOUDFLARE_PAGES_NAME_PATTERN = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;

/** Validate the required Cloudflare Pages project name. */
function assertCloudflareName(value: unknown): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new HostingConfigError('options.name must be a non-empty Cloudflare Pages project name');
  }
  if (value.length > CLOUDFLARE_PAGES_NAME_MAX_LENGTH) {
    throw new HostingConfigError(
      `options.name must be at most ${CLOUDFLARE_PAGES_NAME_MAX_LENGTH} characters`,
    );
  }
  if (!CLOUDFLARE_PAGES_NAME_PATTERN.test(value)) {
    throw new HostingConfigError(
      'options.name must be lowercase letters, digits, and hyphens, starting and ending with a letter or digit',
    );
  }
  return value;
}

/** Reject a non-plain-object options argument shared by the no-option generators. */
function assertPlainOptions(options: unknown, label: string): void {
  if (options === null || typeof options !== 'object' || Array.isArray(options)) {
    throw new HostingConfigError(`${label} must be a plain object`);
  }
}

function buildVercelJson(): string {
  const config = {
    $schema: VERCEL_CONFIG_SCHEMA,
    framework: null,
    buildCommand: 'npm run build',
    installCommand: 'npm ci',
    outputDirectory: 'out',
    cleanUrls: true,
    trailingSlash: false,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

function buildNetlifyToml(): string {
  return [
    '# JSails static export (generated by generateNetlifyStaticConfig).',
    '# Build runs `npm run build` and publishes the static export in out/.',
    '',
    '[build]',
    '  command = "npm run build"',
    '  publish = "out"',
    '',
    '[build.processing.html]',
    '  pretty_urls = true',
    '',
  ].join('\n');
}

function buildWranglerToml(name: string): string {
  return [
    '# JSails static export (generated by generateCloudflarePagesConfig).',
    '# name is the Cloudflare Pages project name; edit it before deploying.',
    '',
    `name = "${name}"`,
    'pages_build_output_dir = "out"',
    '',
  ].join('\n');
}

function buildPagesWorkflow(): string {
  return [
    '# JSails static export deployment to GitHub Pages (generated by JSails).',
    '# Runs `npm run build` and publishes the static export in out/.',
    'name: Deploy static content to Pages',
    '',
    'on:',
    '  push:',
    '    branches: ["main"]',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '  pages: write',
    '  id-token: write',
    '',
    'concurrency:',
    '  group: "pages"',
    '  cancel-in-progress: false',
    '',
    'jobs:',
    '  deploy:',
    '    environment:',
    '      name: github-pages',
    '      url: ${{ steps.deployment.outputs.page_url }}',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '      - name: Setup Node',
    '        uses: actions/setup-node@v4',
    '        with:',
    '          node-version: 20',
    '          cache: npm',
    '      - name: Install dependencies',
    '        run: npm ci',
    '      - name: Build',
    '        run: npm run build',
    '      - name: Setup Pages',
    '        uses: actions/configure-pages@v5',
    '      - name: Upload artifact',
    '        uses: actions/upload-pages-artifact@v3',
    '        with:',
    '          path: out',
    '      - name: Deploy to GitHub Pages',
    '        id: deployment',
    '        uses: actions/deploy-pages@v5',
    '',
  ].join('\n');
}

/**
 * Generate the Vercel static-hosting config: a `vercel.json` that builds with
 * `npm run build` and serves the static export in `out/`. Returns a string
 * only; nothing is written, run, or deployed.
 */
export function generateVercelStaticConfig(options: VercelStaticOptions = {}): VercelStaticFiles {
  assertPlainOptions(options, 'options');
  return { vercelJson: buildVercelJson() };
}

/**
 * Generate the Netlify static-hosting config: a `netlify.toml` that builds
 * with `npm run build`, publishes `out/`, and enables pretty (clean) URLs.
 * Returns a string only; nothing is written, run, or deployed.
 */
export function generateNetlifyStaticConfig(
  options: NetlifyStaticOptions = {},
): NetlifyStaticFiles {
  assertPlainOptions(options, 'options');
  return { netlifyToml: buildNetlifyToml() };
}

/**
 * Generate the Cloudflare Pages static-hosting config: a `wrangler.toml`
 * declaring the project `name` and `pages_build_output_dir = "out"`. The name
 * is a required, validated identifier. Returns a string only; nothing is
 * written, run, or deployed.
 */
export function generateCloudflarePagesConfig(
  options: CloudflarePagesOptions,
): CloudflarePagesFiles {
  assertPlainOptions(options, 'options');
  const name = assertCloudflareName(options.name);
  return { wranglerToml: buildWranglerToml(name) };
}

/**
 * Generate the GitHub Pages static-hosting config: the official static Pages
 * workflow (`.github/workflows/pages.yml`) that checks out, builds, and
 * uploads the `out/` directory as the Pages artifact, plus a `.nojekyll`
 * placeholder marker. Returns strings only; nothing is written, run, or
 * deployed, and no secret is embedded.
 */
export function generateGitHubPagesConfig(options: GitHubPagesOptions = {}): GitHubPagesFiles {
  assertPlainOptions(options, 'options');
  return { workflow: buildPagesWorkflow(), nojekyll: '' };
}
