/**
 * Basecamp ONCE deployment preset (opt-in).
 *
 * ONCE runs a single Docker container, routes HTTP to port 80, probes `GET /up`
 * for a 2xx health response, and mounts its persistent volume at `/storage`
 * (also `/rails/storage`). It injects `BASE_URL` (the full public origin) into
 * the container. ONCE performs **no** database or Valkey provisioning and
 * **never chowns the mounted volume** — the image itself must create and own
 * the storage directories for its runtime user.
 *
 * {@link generateOnceConfig} is a pure string generator in the same family as
 * the Valkey/database/Kamal generators: it never writes files, never runs
 * Docker or ONCE, never opens a connection, and never embeds a secret. It
 * returns three strings — a multi-stage `Dockerfile.once`, a `.dockerignore`,
 * and a `jsails.once.js` ESM wrapper around the app's real `jsails.app.js` —
 * which the caller materializes and builds. The image build still requires a
 * resolvable `jsails` dependency (published, or vendored via a `file:` tarball)
 * and a committed `package-lock.json`; neither is produced here.
 */

/** Generated Dockerfile filename. */
export const ONCE_DOCKERFILE_FILENAME = 'Dockerfile.once';
/** Generated `.dockerignore` filename. */
export const ONCE_DOCKERIGNORE_FILENAME = '.dockerignore';
/** Generated ESM config-wrapper filename. */
export const ONCE_WRAPPER_FILENAME = 'jsails.once.js';

/** Default base image for both stages (Node 24 satisfies the `>=24.11.0` engine). */
export const ONCE_DEFAULT_BASE_IMAGE = 'node:24-bookworm-slim';

/** Container listen host (every interface; ONCE routes HTTP to port 80). */
const ONCE_HOST = '0.0.0.0';
/** Container listen port. */
const ONCE_PORT = 80;
/** Primary persistent-volume mount point ONCE provisions. */
const ONCE_STORAGE_PATH = '/storage';
/** Legacy persistent-volume mount point ONCE also provisions. */
const ONCE_LEGACY_STORAGE_PATH = '/rails/storage';

/** Env var ONCE injects as the full public origin. */
const ONCE_BASE_URL_ENV = 'BASE_URL';

/** In-container bin path of the installed `jsails` CLI (see package.json "bin"). */
const ONCE_CLI_BIN = 'node_modules/.bin/jsails';
/** App config module the wrapper re-exports and overrides. */
const ONCE_APP_CONFIG_MODULE = './jsails.app.js';

/** Raised for any invalid ONCE preset option. Messages never embed input. */
export class OnceConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'OnceConfigError';
  }
}

/** Options for {@link generateOnceConfig}. */
export interface OnceConfigOptions {
  /** Node base image for both stages. Defaults to {@link ONCE_DEFAULT_BASE_IMAGE}. */
  baseImage?: string;
}

/** Generated ONCE files as strings. */
export interface OnceConfigFiles {
  /** `Dockerfile.once` content: multi-stage builder + slim production runtime. */
  dockerfile: string;
  /** `.dockerignore` content: build output, dependencies, and secrets excluded. */
  dockerignore: string;
  /** `jsails.once.js` content: ESM wrapper mapping ONCE env onto the app config. */
  jsailsConfig: string;
}

/** Control characters (including newlines) that would break the Dockerfile. */
const CONTROL_PATTERN = /[\u0000-\u001F\u007F]/;

/** Docker image reference: registry/namespace/name, tag, or digest. */
const IMAGE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/:\-@]*$/;

/** Validate the base image reference (no shell/control characters). */
function assertBaseImage(value: unknown): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new OnceConfigError('options.baseImage must be a non-empty image reference');
  }
  if (CONTROL_PATTERN.test(value) || !IMAGE_PATTERN.test(value)) {
    throw new OnceConfigError(
      'options.baseImage contains characters that are not valid in a Docker image reference',
    );
  }
  return value;
}

function buildDockerfile(baseImage: string): string {
  return [
    '# syntax=docker/dockerfile:1',
    '',
    '# JSails ONCE deployment image (generated by generateOnceConfig).',
    '#',
    '# Two stages: a builder that installs all dependencies and compiles the app,',
    '# then a slim runtime that carries only production dependencies and the built',
    '# output. ONCE runs the image, routes HTTP to port 80, probes GET /up, and',
    '# mounts its persistent volume at /storage (plus the legacy /rails/storage).',
    '# ONCE never chowns the volume, so this image creates and owns those',
    '# directories as the `node` user before dropping privileges.',
    '',
    '# ---- builder -------------------------------------------------------------',
    `FROM ${baseImage} AS builder`,
    'WORKDIR /app',
    '',
    '# Install everything, including dev dependencies (tsc, vite, ...). `npm ci`',
    '# requires a committed package-lock.json and a resolvable `jsails` dependency',
    '# (published, or vendored via a file: tarball in package.json).',
    'COPY package.json package-lock.json ./',
    'RUN npm ci',
    '',
    '# Compile the app: server code into dist/, browser assets into public/assets/,',
    '# and the static export into out/. out/ is not required for SSR and is not',
    '# copied into the runtime image.',
    'COPY . .',
    'RUN npm run build',
    '',
    '# ---- runtime --------------------------------------------------------------',
    `FROM ${baseImage} AS runtime`,
    'WORKDIR /app',
    'ENV NODE_ENV=production',
    '',
    '# Production dependencies only.',
    'COPY package.json package-lock.json ./',
    'RUN npm ci --omit=dev',
    '',
    '# Built output and configs. The static export (out/) is deliberately omitted:',
    '# the app is served as SSR, not from static files.',
    'COPY --from=builder /app/dist ./dist',
    'COPY --from=builder /app/public ./public',
    'COPY jsails.app.js ./jsails.app.js',
    `COPY ${ONCE_WRAPPER_FILENAME} ./${ONCE_WRAPPER_FILENAME}`,
    '',
    '# ONCE mounts its persistent volume at /storage (and /rails/storage) but',
    '# never chowns it, so the image must create and own those directories for its',
    '# runtime user before it drops privileges.',
    `RUN mkdir -p ${ONCE_STORAGE_PATH} ${ONCE_LEGACY_STORAGE_PATH} && chown -R node:node ${ONCE_STORAGE_PATH} ${ONCE_LEGACY_STORAGE_PATH}`,
    '',
    '# Run as the unprivileged node user.',
    'USER node',
    `EXPOSE ${ONCE_PORT}`,
    '',
    '# The jsails CLI is installed as the `jsails` bin (jsails package.json "bin":',
    '# `jsails` -> ./dist/src/cli.js, i.e. node_modules/jsails/dist/src/cli.js once',
    '# installed). Invoke it by its node_modules/.bin path so the command does not',
    "# depend on PATH; the bin's shebang resolves the runtime.",
    `CMD ["${ONCE_CLI_BIN}", "serve", "--config", "${ONCE_WRAPPER_FILENAME}"]`,
    '',
  ].join('\n');
}

function buildDockerignore(): string {
  return [
    '# Generated by JSails for the ONCE image. Keeps build output, dependencies,',
    '# persistent data, and secrets out of the Docker build context.',
    '',
    'node_modules',
    'dist',
    'public/assets',
    'out',
    'storage',
    '.git',
    'test-results',
    'playwright-report',
    '.env',
    '.env.*',
    '',
  ].join('\n');
}

function buildJsailsConfig(): string {
  return [
    '// JSails ONCE wrapper (generated by generateOnceConfig). ONCE builds and',
    '// runs this image, injecting BASE_URL into the container environment. This',
    '// wrapper imports the real app config and overrides only the values ONCE',
    '// owns; every other field is preserved from jsails.app.js.',
    '',
    `import appConfig from '${ONCE_APP_CONFIG_MODULE}';`,
    '',
    'export default {',
    '  ...appConfig,',
    '  // ONCE routes HTTP to port 80, so bind every interface and that port.',
    `  host: '${ONCE_HOST}',`,
    `  port: ${ONCE_PORT},`,
    '  // ONCE mounts its persistent volume at /storage (and /rails/storage); serve',
    '  // creates this directory, which the image already owns (see Dockerfile.once).',
    `  storage: '${ONCE_STORAGE_PATH}',`,
    "  // BASE_URL is ONCE's full public origin. It is optional for apps: when set",
    "  // it overrides the app's own publicOrigin so CSRF/session origin checks",
    '  // match the public URL; when unset the original publicOrigin is kept.',
    `  ...(process.env.${ONCE_BASE_URL_ENV} ? { publicOrigin: process.env.${ONCE_BASE_URL_ENV} } : {}),`,
    '};',
    '',
  ].join('\n');
}

/**
 * Generate the Basecamp ONCE deployment preset: a `Dockerfile.once`, a
 * `.dockerignore`, and a `jsails.once.js` wrapper config. Returns strings only;
 * nothing is written to disk, run, or deployed, and no secret is ever embedded.
 */
export function generateOnceConfig(options: OnceConfigOptions = {}): OnceConfigFiles {
  if (options === null || typeof options !== 'object' || Array.isArray(options)) {
    throw new OnceConfigError('options must be a plain object');
  }
  const baseImage = assertBaseImage(options.baseImage ?? ONCE_DEFAULT_BASE_IMAGE);
  return {
    dockerfile: buildDockerfile(baseImage),
    dockerignore: buildDockerignore(),
    jsailsConfig: buildJsailsConfig(),
  };
}
